name: Terraform Deployment

on:
  push:
    branches:
      - main  # Runs on every push to main branch
  pull_request:
    branches:
      - main  # Runs on pull request to main branch
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Change to the latest version if needed

      - name: Initialize Terraform
        run: terraform init
        working-directory: multi_tier_arch

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: multi_tier_arch

      - name: Terraform output check
        run: terraform output
        working-directory: multi_tier_arch
          
 #     - name: Force Unlock State
 #       run: terraform force-unlock -force 980ea3d9-224a-1f56-9c2b-3732a51e54eb || true
 #       working-directory: multi_tier_arch

      - name: Terraform Plan
        run: terraform plan
        working-directory: multi_tier_arch

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only applies changes on main branch
        run: terraform apply -auto-approve
        working-directory: multi_tier_arch

  manual_destroy:
    name: Manual Destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps: 
      - name: Checkout Repository
        run: actions/checkout@v3

      - name: Setup Terraform
        run: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy (Manual)
        run: terraform destroy -auto-approve